tap "versent/homebrew-taps"
cask_args appdir: "/Applications"

# Requires iCloud Sign In
#brew "mas"

cask "iterm2"
cask "visual-studio-code"
cask "insomnia"
cask "lepton"
cask "zoom"
cask "whatsapp"
cask "spotify"
cask "hiddenbar"
cask "slack"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "docker"
cask "dropbox"
cask "grammarly"

# GNU instead of MacOS utilities
brew "grep"
brew "curl"
brew "wget"
brew "watch"
brew "less"
brew "more"
brew "bash"

# MacOS App Store
#mas "Magnet", id: 441258766

# Packages
brew "awscli"
brew "pyenv"
brew "pyenv-virtualenv"
brew "saml2aws"
brew "telnet"
brew "terraform-docs"
brew "the_silver_searcher"
brew "vim"
brew "tmux"
brew "fzf"
brew "git"
brew "bat"
brew "ansible"
brew "ipython"
brew "jq"
brew "kafkacat"
brew "kubernetes-cli"
brew "kubeseal"
brew "kustomize"
brew "nmap"
brew "packer"
